version: '3'
services:
  registry:
    image: registry:latest
    container_name: registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ${PWD}/data/registry:/var/lib/registry
networks:
  default:
    external:
      name: compose-bridge