version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx_v1.2
    ports: 
      - "88:80"
    volumes:
      - ${PWD}/data/build:/opt/build      
    restart: always
    privileged: true
    #network_mode: host
networks:
  default:
    external:
      name: compose-bridge
