version: "3"
services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    logging:
      driver: json-file
      options:
        max-size: 50m
networks:
  default:
    external:
      name: compose-bridge